---
# tasks file for ansible-apache_mod_rpaf_role
- name: Load the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure mod_rpaf is installed
  package:
    name: "{{ item }}"
  with_items: "{{ __apache_mod_rpaf_pkgs }}"
  notify: reload apache

- name: Load rpaf configuration
  template:
    src: "rpaf.conf.j2"
    dest: "/etc/apache2/mods-available/rpaf.conf"
  notify: reload apache
